name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build main
      run: cargo build --verbose
      
    - name: Build repairer
      run: cd src/repair-refactoring && cargo build --verbose
      
    - name: Build borrower
      run: cd ../the-borrower && cargo build --verbose
